base_locale: zh-CN

locales: [zh-CN, en, fr, ru]

# source: zh-CN原始文件存放路径， translation: 翻译文件存放路径，translated：翻译后的文件存放路径
# read: 存放对比文件的地方，默认为tmp/

data:
  source:
    - source/
  translation:
    - translation/
  translated:
    - translated/
  yaml:
    write:
      ## do not wrap lines at 80 characters (override default)
      line_width: 96

#search:
#  paths:
#    - spec/
#  exclude:
#    - 'tmp/*'

## Google Translate
#translation:
#  api_key: "xxxxx"