base_locale: zh-CN

locals: [zh-CN, en]

data:
  read:
    - config/locales/origin/%{locale}.yml
    - config/locales/dictionary/%{locale}.yml

  write:
    - config/locales/dictionary/%{locale}.yml
  yaml:
    write:
      ## do not wrap lines at 80 characters (override default)
      line_width: 96

search:
  paths:
    - spec/
  exclude:
    - 'tmp/*'

## Google Translate
#translation:
#  api_key: "xxxxx"