base_locale: zh-CN
#internal_locale: zh-CN
locals: [zh-CN, en]

data:
  read:
    - config/locales/origin/%{locale}.yml
    - config/locales/dictionary/%{locale}.yml

  write:
    - config/locales/normalize/*.%{locale}.yml
  yaml:
    write:
      ## do not wrap lines at 80 characters (override default)
      line_width: 96

# Find translate calls
search:
  paths:
    - template/
  exclude:
    - 'tmp/*'

## Google Translate
#translation:
#  api_key: "xxxxx"